/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Source: docs/openapi.json
 * Regenerate with: npm run gen:api
 * This must be re-run whenever the API spec changes; the app's types are only as
 * correct as the spec copy in docs/openapi.json.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regions */
        get: operations["list_regions_api_v1_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{region_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Region Detail */
        get: operations["get_region_detail_api_v1_regions__region_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Attributions
         * @description Data credits to display (e.g. in a page footer) on every screen. Required ones are
         *     a licence condition; the current-aqi response also carries the CPCB text next to the
         *     readings it covers.
         */
        get: operations["list_attributions_api_v1_attributions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{station_id}/current-aqi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Aqi
         * @description Official CPCB AQI right now (no forecast involved), when CPCB has
         *     a recent reading for this station.
         */
        get: operations["get_current_aqi_api_v1_stations__station_id__current_aqi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stations
         * @description Stations with a current forecast come first: the upstream sensor feed
         *     lags for most of the network, so most stations cannot be forecast right now
         *     and clients need to tell them apart.
         */
        get: operations["list_stations_api_v1_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Station */
        get: operations["get_station_api_v1_stations__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_api_v1_forecast__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/{station_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast History */
        get: operations["get_forecast_history_api_v1_forecast__station_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Health */
        get: operations["get_model_health_api_v1_model_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/{station_id}/exceedance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exceedance Summary */
        get: operations["get_exceedance_summary_api_v1_forecast__station_id__exceedance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscription Availability
         * @description Lets a client say up front that sign-ups are invite-only (demo mode).
         */
        get: operations["subscription_availability_api_v1_subscriptions_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Subscription
         * @description Ask to subscribe. Always answers the same 202 body (no subscriber id, no
         *     hint whether the address is already known). Emails a confirmation link for
         *     a new/pending address, or a manage link for a confirmed one; nothing is
         *     activated or modified until the mailbox owner uses a link.
         *
         *     In demo mode an address that is not invited gets the same 202, but nothing
         *     is stored or sent: the reply must not reveal who is invited, and we keep no
         *     data about people who cannot use the service.
         */
        post: operations["request_subscription_api_v1_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Subscription
         * @description Single-use: the token is erased from the row the moment it works.
         */
        post: operations["confirm_subscription_api_v1_subscriptions_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/manage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manage Subscription
         * @description Replace the stations/pollutants of a confirmed subscription (and switch
         *     it on, which is how someone who unsubscribed re-subscribes). Authorised
         *     only by the emailed manage token.
         */
        post: operations["manage_subscription_api_v1_subscriptions_manage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unsubscribe */
        post: operations["unsubscribe_api_v1_subscriptions_unsubscribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Subscription
         * @description Erase the subscription and its send history ("delete my data"). Same
         *     tokens as unsubscribing. Irreversible; subscribing again starts over.
         */
        post: operations["delete_subscription_api_v1_subscriptions_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/unsubscribe/one-click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unsubscribe One Click
         * @description RFC 8058 target of the List-Unsubscribe header: the mail provider POSTs
         *     `List-Unsubscribe=One-Click` (form-encoded) with no user interaction.
         */
        post: operations["unsubscribe_one_click_api_v1_subscriptions_unsubscribe_one_click_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AqiCategoryOut */
        AqiCategoryOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** AttributionOut */
        AttributionOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Url */
            url: string | null;
            /** Required */
            required: boolean;
            /** Applies To */
            applies_to: string;
        };
        /** CurrentAqiOut */
        CurrentAqiOut: {
            /** Station Id */
            station_id: string;
            /** As Of */
            as_of: string | null;
            /** Is Current */
            is_current: boolean;
            /** Aqi Standard */
            aqi_standard: string | null;
            /** Timezone */
            timezone: string | null;
            overall: components["schemas"]["OverallAqiOut"] | null;
            /** At Or Above Health Threshold */
            at_or_above_health_threshold?: boolean | null;
            /** Pollutants */
            pollutants: components["schemas"]["PollutantAqiOut"][];
            /** Attribution */
            attribution: string;
        };
        /**
         * ExceedanceDayOut
         * @description One calendar day. What the values describe depends on the summary's `target`.
         *
         *     "daily_mean" (graded verdicts, owner decision 2026-10-02): everything is about the day's
         *     MEAN concentration. aqi_category is the worst category that mean reaches with the service's
         *     decision probability, and verdict follows from it: go below the region's health-threshold
         *     category, caution in it, no-go from the next one up.
         *
         *     "hourly": the day is represented by ONE forecast hour (the run's anchor hour + N x 24 h).
         *     exceedance_flag is true when that hour is likely above the health threshold, and
         *     aqi_category is the category of its upper quantile.
         */
        ExceedanceDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Exceedance Flag */
            exceedance_flag: boolean;
            /** Exceedance Probability */
            exceedance_probability: number;
            /** Worst Case Value */
            worst_case_value: number;
            /** Aqi Category */
            aqi_category: string;
            /** Verdict */
            verdict?: string | null;
            /** Expected Value */
            expected_value?: number | null;
            /** Expected Sub Index */
            expected_sub_index?: number | null;
        };
        /** ExceedanceSummaryOut */
        ExceedanceSummaryOut: {
            /** Station Id */
            station_id: string;
            /** Pollutant */
            pollutant: string;
            /** Timezone */
            timezone?: string | null;
            /** Forecast Made At */
            forecast_made_at?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /**
             * Target
             * @default hourly
             */
            target: string;
            /** Days */
            days: components["schemas"]["ExceedanceDayOut"][];
            /** Overall Recommendation */
            overall_recommendation: string;
        };
        /** ForecastPointOut */
        ForecastPointOut: {
            /**
             * Target Time
             * Format: date-time
             */
            target_time: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Point Forecast */
            point_forecast: number;
            /** Quantile Low */
            quantile_low: number;
            /** Quantile High */
            quantile_high: number;
            /** Exceedance Probability */
            exceedance_probability: number;
            /** Exceedance Flag */
            exceedance_flag: boolean;
        };
        /** ForecastSeriesOut */
        ForecastSeriesOut: {
            /** Station Id */
            station_id: string;
            /** Pollutant */
            pollutant: string;
            /** Forecast Made At */
            forecast_made_at: string | null;
            /** Timezone */
            timezone?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /**
             * Target
             * @default hourly
             */
            target: string;
            /** Forecasts */
            forecasts: components["schemas"]["ForecastPointOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryOut */
        HistoryOut: {
            /** Station Id */
            station_id: string;
            /** Pollutant */
            pollutant: string;
            /** Timezone */
            timezone?: string | null;
            /**
             * Target
             * @default hourly
             */
            target: string;
            /** Points */
            points: components["schemas"]["HistoryPointOut"][];
        };
        /** HistoryPointOut */
        HistoryPointOut: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Actual */
            actual: number | null;
            /** Forecast Value */
            forecast_value: number | null;
        };
        /** ManageIn */
        ManageIn: {
            /** Station Ids */
            station_ids: string[];
            /** Pollutants */
            pollutants: components["schemas"]["Pollutant"][];
            /** Token */
            token: string;
        };
        /** ModelHealthOut */
        ModelHealthOut: {
            /** Station Id */
            station_id: string;
            /** Pollutant */
            pollutant: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Precision */
            precision: number | null;
            /** Recall */
            recall: number | null;
            /** F1 */
            f1: number | null;
            /** Mae */
            mae: number | null;
            /** Rmse */
            rmse: number | null;
            /**
             * Evaluation Window End
             * Format: date-time
             */
            evaluation_window_end: string;
        };
        /** OverallAqiOut */
        OverallAqiOut: {
            /** Aqi */
            aqi: number;
            /** Category */
            category: string;
            /** Driver */
            driver: string;
        };
        /**
         * OverviewCurrentAqiOut
         * @description GET /stations/{id}/current-aqi without the per-station constants (see OverviewOut).
         */
        OverviewCurrentAqiOut: {
            /** As Of */
            as_of: string | null;
            /** Is Current */
            is_current: boolean;
            overall: components["schemas"]["OverallAqiOut"] | null;
            /** At Or Above Health Threshold */
            at_or_above_health_threshold?: boolean | null;
            /** Pollutants */
            pollutants: components["schemas"]["PollutantAqiOut"][];
        };
        /**
         * OverviewOut
         * @description Everything a map needs for every active station, in one response.
         */
        OverviewOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Attribution */
            attribution: string;
            /** Stations */
            stations: components["schemas"]["OverviewStationOut"][];
        };
        /** OverviewStationOut */
        OverviewStationOut: {
            /** Station Id */
            station_id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** City */
            city: string;
            /** Region Id */
            region_id?: string | null;
            current_aqi: components["schemas"]["OverviewCurrentAqiOut"];
            /** Outlooks */
            outlooks: components["schemas"]["ExceedanceSummaryOut"][];
        };
        /**
         * Pollutant
         * @enum {string}
         */
        Pollutant: "pm25" | "no2";
        /** PollutantAqiOut */
        PollutantAqiOut: {
            /** Pollutant Id */
            pollutant_id: string;
            /** Sub Index Avg */
            sub_index_avg: number | null;
            /** Sub Index Min */
            sub_index_min: number | null;
            /** Sub Index Max */
            sub_index_max: number | null;
            /** Category */
            category: string | null;
        };
        /** PollutantInfoOut */
        PollutantInfoOut: {
            /** Id */
            id: string;
            /** Unit */
            unit: string;
            /** Health Threshold Concentration */
            health_threshold_concentration: number | null;
            /** Threshold Averaging */
            threshold_averaging: string | null;
        };
        /** RegionOut */
        RegionOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** Timezone */
            timezone: string;
            /** Bbox */
            bbox: number[];
            /** Aqi Standard */
            aqi_standard: string;
            /** Pollutants */
            pollutants: string[];
            /** Pollutant Details */
            pollutant_details: components["schemas"]["PollutantInfoOut"][];
            /** Aqi Categories */
            aqi_categories: components["schemas"]["AqiCategoryOut"][];
            /** Health Threshold Category */
            health_threshold_category: string;
        };
        /** StationDetailOut */
        StationDetailOut: {
            /** Station Id */
            station_id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** City */
            city: string;
            /** Is Active */
            is_active: boolean;
            /** Region Id */
            region_id?: string | null;
            /** Latest Observed At */
            latest_observed_at?: string | null;
            /**
             * Has Current Forecast
             * @default false
             */
            has_current_forecast: boolean;
            /**
             * Has Current Aqi
             * @default false
             */
            has_current_aqi: boolean;
        };
        /** StationOut */
        StationOut: {
            /** Station Id */
            station_id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** City */
            city: string;
            /** Is Active */
            is_active: boolean;
            /** Region Id */
            region_id?: string | null;
            /** Latest Observed At */
            latest_observed_at?: string | null;
            /**
             * Has Current Forecast
             * @default false
             */
            has_current_forecast: boolean;
            /**
             * Has Current Aqi
             * @default false
             */
            has_current_aqi: boolean;
        };
        /**
         * SubscriptionAvailabilityOut
         * @description Whether anyone may sign up. Never lists or hints at the invited addresses.
         */
        SubscriptionAvailabilityOut: {
            /** Open */
            open: boolean;
            /** Message */
            message: string;
        };
        /** SubscriptionIn */
        SubscriptionIn: {
            /** Station Ids */
            station_ids: string[];
            /** Pollutants */
            pollutants: components["schemas"]["Pollutant"][];
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * SubscriptionRequestOut
         * @description Identical for every valid request, whatever the email's state, so the
         *     endpoint cannot be used to test whether an address is subscribed.
         */
        SubscriptionRequestOut: {
            /**
             * Status
             * @default check-your-email
             */
            status: string;
            /**
             * Message
             * @default If this address can be subscribed, an email with a link has been sent to it. Nothing changes until the owner of the address opens that link.
             */
            message: string;
        };
        /** SubscriptionStatusOut */
        SubscriptionStatusOut: {
            /** Status */
            status: string;
        };
        /** TokenIn */
        TokenIn: {
            /** Token */
            token: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_regions_api_v1_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"][];
                };
            };
        };
    };
    get_region_detail_api_v1_regions__region_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attributions_api_v1_attributions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionOut"][];
                };
            };
        };
    };
    get_current_aqi_api_v1_stations__station_id__current_aqi_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentAqiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stations_api_v1_stations_get: {
        parameters: {
            query?: {
                region_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_station_api_v1_stations__station_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_api_v1_forecast__station_id__get: {
        parameters: {
            query?: {
                pollutant?: components["schemas"]["Pollutant"];
                horizon_days?: number | null;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_history_api_v1_forecast__station_id__history_get: {
        parameters: {
            query?: {
                pollutant?: components["schemas"]["Pollutant"];
                lookback_days?: number;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_health_api_v1_model_health_get: {
        parameters: {
            query?: {
                station_id?: string | null;
                pollutant?: components["schemas"]["Pollutant"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelHealthOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exceedance_summary_api_v1_forecast__station_id__exceedance_get: {
        parameters: {
            query?: {
                pollutant?: components["schemas"]["Pollutant"];
                days_ahead?: number;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceedanceSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_v1_overview_get: {
        parameters: {
            query?: {
                region_id?: string | null;
                days_ahead?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscription_availability_api_v1_subscriptions_availability_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionAvailabilityOut"];
                };
            };
        };
    };
    request_subscription_api_v1_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_subscription_api_v1_subscriptions_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manage_subscription_api_v1_subscriptions_manage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_api_v1_subscriptions_unsubscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_api_v1_subscriptions_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_one_click_api_v1_subscriptions_unsubscribe_one_click_post: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
