/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regions */
        get: operations["list_regions_api_v1_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{region_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Region Detail */
        get: operations["get_region_detail_api_v1_regions__region_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{station_id}/current-aqi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Aqi
         * @description Official CPCB AQI right now (no forecast involved), when data.gov.in has
         *     a recent reading for this station.
         */
        get: operations["get_current_aqi_api_v1_stations__station_id__current_aqi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stations
         * @description Stations with a current forecast come first: the upstream sensor feed
         *     lags for most of the network, so most stations cannot be forecast right now
         *     and clients need to tell them apart.
         */
        get: operations["list_stations_api_v1_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Station */
        get: operations["get_station_api_v1_stations__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_api_v1_forecast__station_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/{station_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast History */
        get: operations["get_forecast_history_api_v1_forecast__station_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Health */
        get: operations["get_model_health_api_v1_model_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/{station_id}/exceedance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exceedance Summary */
        get: operations["get_exceedance_summary_api_v1_forecast__station_id__exceedance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Subscription
         * @description Creates a subscription for a NEW email only.
         *
         *     Deliberately never modifies, reactivates or reveals an existing row: with
         *     no proof of email ownership, an upsert would let anyone overwrite a
         *     victim's stations and read back their subscriber_id (the only credential
         *     for DELETE). A 409 is returned instead. Changing or re-enabling a
         *     subscription needs an owner-verified flow (emailed confirmation token),
         *     which is not built yet.
         */
        post: operations["create_subscription_api_v1_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{subscriber_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unsubscribe */
        delete: operations["unsubscribe_api_v1_subscriptions__subscriber_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AqiCategoryOut */
        AqiCategoryOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** CurrentAqiOut */
        CurrentAqiOut: {
            /** Station Id */
            station_id: string;
            /** As Of */
            as_of: string | null;
            /** Is Current */
            is_current: boolean;
            /** Aqi Standard */
            aqi_standard: string | null;
            /** Timezone */
            timezone: string | null;
            overall: components["schemas"]["OverallAqiOut"] | null;
            /** At Or Above Health Threshold */
            at_or_above_health_threshold?: boolean | null;
            /** Pollutants */
            pollutants: components["schemas"]["PollutantAqiOut"][];
            /** Attribution */
            attribution: string;
        };
        /** ExceedanceDayOut */
        ExceedanceDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Exceedance Flag */
            exceedance_flag: boolean;
            /** Exceedance Probability */
            exceedance_probability: number;
            /** Worst Case Value */
            worst_case_value: number;
            /** Aqi Category */
            aqi_category: string;
        };
        /** ExceedanceSummaryOut */
        ExceedanceSummaryOut: {
            /** Station Id */
            station_id: string;
            /** Pollutant */
            pollutant: string;
            /** Timezone */
            timezone?: string | null;
            /** Days */
            days: components["schemas"]["ExceedanceDayOut"][];
            /** Overall Recommendation */
            overall_recommendation: string;
        };
        /** ForecastPointOut */
        ForecastPointOut: {
            /**
             * Target Time
             * Format: date-time
             */
            target_time: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Point Forecast */
            point_forecast: number;
            /** Quantile Low */
            quantile_low: number;
            /** Quantile High */
            quantile_high: number;
            /** Exceedance Probability */
            exceedance_probability: number;
            /** Exceedance Flag */
            exceedance_flag: boolean;
        };
        /** ForecastSeriesOut */
        ForecastSeriesOut: {
            /** Station Id */
            station_id: string;
            /** Pollutant */
            pollutant: string;
            /** Forecast Made At */
            forecast_made_at: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /** Forecasts */
            forecasts: components["schemas"]["ForecastPointOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryOut */
        HistoryOut: {
            /** Station Id */
            station_id: string;
            /** Pollutant */
            pollutant: string;
            /** Points */
            points: components["schemas"]["HistoryPointOut"][];
        };
        /** HistoryPointOut */
        HistoryPointOut: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Actual */
            actual: number | null;
            /** Forecast Value */
            forecast_value: number | null;
        };
        /** ModelHealthOut */
        ModelHealthOut: {
            /** Station Id */
            station_id: string;
            /** Pollutant */
            pollutant: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Precision */
            precision: number | null;
            /** Recall */
            recall: number | null;
            /** F1 */
            f1: number | null;
            /** Mae */
            mae: number | null;
            /** Rmse */
            rmse: number | null;
            /**
             * Evaluation Window End
             * Format: date-time
             */
            evaluation_window_end: string;
        };
        /** OverallAqiOut */
        OverallAqiOut: {
            /** Aqi */
            aqi: number;
            /** Category */
            category: string;
            /** Driver */
            driver: string;
        };
        /**
         * Pollutant
         * @enum {string}
         */
        Pollutant: "pm25" | "no2";
        /** PollutantAqiOut */
        PollutantAqiOut: {
            /** Pollutant Id */
            pollutant_id: string;
            /** Sub Index Avg */
            sub_index_avg: number | null;
            /** Sub Index Min */
            sub_index_min: number | null;
            /** Sub Index Max */
            sub_index_max: number | null;
            /** Category */
            category: string | null;
        };
        /** RegionOut */
        RegionOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** Timezone */
            timezone: string;
            /** Bbox */
            bbox: number[];
            /** Aqi Standard */
            aqi_standard: string;
            /** Pollutants */
            pollutants: string[];
            /** Aqi Categories */
            aqi_categories: components["schemas"]["AqiCategoryOut"][];
            /** Health Threshold Category */
            health_threshold_category: string;
        };
        /** StationDetailOut */
        StationDetailOut: {
            /** Station Id */
            station_id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** City */
            city: string;
            /** Is Active */
            is_active: boolean;
            /** Region Id */
            region_id?: string | null;
            /** Latest Observed At */
            latest_observed_at?: string | null;
            /**
             * Has Current Forecast
             * @default false
             */
            has_current_forecast: boolean;
            /**
             * Has Current Aqi
             * @default false
             */
            has_current_aqi: boolean;
        };
        /** StationOut */
        StationOut: {
            /** Station Id */
            station_id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** City */
            city: string;
            /** Is Active */
            is_active: boolean;
            /** Region Id */
            region_id?: string | null;
            /** Latest Observed At */
            latest_observed_at?: string | null;
            /**
             * Has Current Forecast
             * @default false
             */
            has_current_forecast: boolean;
            /**
             * Has Current Aqi
             * @default false
             */
            has_current_aqi: boolean;
        };
        /** SubscriptionIn */
        SubscriptionIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Station Ids */
            station_ids: string[];
            /** Pollutants */
            pollutants: components["schemas"]["Pollutant"][];
        };
        /** SubscriptionOut */
        SubscriptionOut: {
            /**
             * Subscriber Id
             * Format: uuid
             */
            subscriber_id: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_regions_api_v1_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"][];
                };
            };
        };
    };
    get_region_detail_api_v1_regions__region_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_aqi_api_v1_stations__station_id__current_aqi_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentAqiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stations_api_v1_stations_get: {
        parameters: {
            query?: {
                region_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_station_api_v1_stations__station_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_api_v1_forecast__station_id__get: {
        parameters: {
            query?: {
                pollutant?: components["schemas"]["Pollutant"];
                horizon_days?: number | null;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_history_api_v1_forecast__station_id__history_get: {
        parameters: {
            query?: {
                pollutant?: components["schemas"]["Pollutant"];
                lookback_days?: number;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_health_api_v1_model_health_get: {
        parameters: {
            query?: {
                station_id?: string | null;
                pollutant?: components["schemas"]["Pollutant"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelHealthOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exceedance_summary_api_v1_forecast__station_id__exceedance_get: {
        parameters: {
            query?: {
                pollutant?: components["schemas"]["Pollutant"];
                days_ahead?: number;
            };
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExceedanceSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subscription_api_v1_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_api_v1_subscriptions__subscriber_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriber_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
