/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as OperatorModelHealthRouteImport } from './routes/operator.model-health'
import { Route as RRegionIdRouteImport } from './routes/r.$regionId'
import { Route as SubscriptionsConfirmRouteImport } from './routes/subscriptions.confirm'
import { Route as SubscriptionsManageRouteImport } from './routes/subscriptions.manage'
import { Route as SubscriptionsUnsubscribeRouteImport } from './routes/subscriptions.unsubscribe'
import { Route as RRegionIdIndexRouteImport } from './routes/r.$regionId.index'
import { Route as RRegionIdSStationIdRouteImport } from './routes/r.$regionId.s.$stationId'
import { Route as RRegionIdSStationIdIndexRouteImport } from './routes/r.$regionId.s.$stationId.index'
import { Route as RRegionIdSStationIdForecastRouteImport } from './routes/r.$regionId.s.$stationId.forecast'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorModelHealthRoute = OperatorModelHealthRouteImport.update({
  id: '/operator/model-health',
  path: '/operator/model-health',
  getParentRoute: () => rootRouteImport,
} as any)
const RRegionIdRoute = RRegionIdRouteImport.update({
  id: '/r/$regionId',
  path: '/r/$regionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsConfirmRoute = SubscriptionsConfirmRouteImport.update({
  id: '/subscriptions/confirm',
  path: '/subscriptions/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsManageRoute = SubscriptionsManageRouteImport.update({
  id: '/subscriptions/manage',
  path: '/subscriptions/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsUnsubscribeRoute =
  SubscriptionsUnsubscribeRouteImport.update({
    id: '/subscriptions/unsubscribe',
    path: '/subscriptions/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const RRegionIdIndexRoute = RRegionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RRegionIdRoute,
} as any)
const RRegionIdSStationIdRoute = RRegionIdSStationIdRouteImport.update({
  id: '/s/$stationId',
  path: '/s/$stationId',
  getParentRoute: () => RRegionIdRoute,
} as any)
const RRegionIdSStationIdIndexRoute =
  RRegionIdSStationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RRegionIdSStationIdRoute,
  } as any)
const RRegionIdSStationIdForecastRoute =
  RRegionIdSStationIdForecastRouteImport.update({
    id: '/forecast',
    path: '/forecast',
    getParentRoute: () => RRegionIdSStationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subscribe': typeof SubscribeRoute
  '/operator/model-health': typeof OperatorModelHealthRoute
  '/r/$regionId': typeof RRegionIdRouteWithChildren
  '/subscriptions/confirm': typeof SubscriptionsConfirmRoute
  '/subscriptions/manage': typeof SubscriptionsManageRoute
  '/subscriptions/unsubscribe': typeof SubscriptionsUnsubscribeRoute
  '/r/$regionId/': typeof RRegionIdIndexRoute
  '/r/$regionId/s/$stationId': typeof RRegionIdSStationIdRouteWithChildren
  '/r/$regionId/s/$stationId/forecast': typeof RRegionIdSStationIdForecastRoute
  '/r/$regionId/s/$stationId/': typeof RRegionIdSStationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscribe': typeof SubscribeRoute
  '/operator/model-health': typeof OperatorModelHealthRoute
  '/subscriptions/confirm': typeof SubscriptionsConfirmRoute
  '/subscriptions/manage': typeof SubscriptionsManageRoute
  '/subscriptions/unsubscribe': typeof SubscriptionsUnsubscribeRoute
  '/r/$regionId': typeof RRegionIdIndexRoute
  '/r/$regionId/s/$stationId/forecast': typeof RRegionIdSStationIdForecastRoute
  '/r/$regionId/s/$stationId': typeof RRegionIdSStationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subscribe': typeof SubscribeRoute
  '/operator/model-health': typeof OperatorModelHealthRoute
  '/r/$regionId': typeof RRegionIdRouteWithChildren
  '/subscriptions/confirm': typeof SubscriptionsConfirmRoute
  '/subscriptions/manage': typeof SubscriptionsManageRoute
  '/subscriptions/unsubscribe': typeof SubscriptionsUnsubscribeRoute
  '/r/$regionId/': typeof RRegionIdIndexRoute
  '/r/$regionId/s/$stationId': typeof RRegionIdSStationIdRouteWithChildren
  '/r/$regionId/s/$stationId/forecast': typeof RRegionIdSStationIdForecastRoute
  '/r/$regionId/s/$stationId/': typeof RRegionIdSStationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subscribe'
    | '/operator/model-health'
    | '/r/$regionId'
    | '/subscriptions/confirm'
    | '/subscriptions/manage'
    | '/subscriptions/unsubscribe'
    | '/r/$regionId/'
    | '/r/$regionId/s/$stationId'
    | '/r/$regionId/s/$stationId/forecast'
    | '/r/$regionId/s/$stationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subscribe'
    | '/operator/model-health'
    | '/subscriptions/confirm'
    | '/subscriptions/manage'
    | '/subscriptions/unsubscribe'
    | '/r/$regionId'
    | '/r/$regionId/s/$stationId/forecast'
    | '/r/$regionId/s/$stationId'
  id:
    | '__root__'
    | '/'
    | '/subscribe'
    | '/operator/model-health'
    | '/r/$regionId'
    | '/subscriptions/confirm'
    | '/subscriptions/manage'
    | '/subscriptions/unsubscribe'
    | '/r/$regionId/'
    | '/r/$regionId/s/$stationId'
    | '/r/$regionId/s/$stationId/forecast'
    | '/r/$regionId/s/$stationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubscribeRoute: typeof SubscribeRoute
  OperatorModelHealthRoute: typeof OperatorModelHealthRoute
  RRegionIdRoute: typeof RRegionIdRouteWithChildren
  SubscriptionsConfirmRoute: typeof SubscriptionsConfirmRoute
  SubscriptionsManageRoute: typeof SubscriptionsManageRoute
  SubscriptionsUnsubscribeRoute: typeof SubscriptionsUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/model-health': {
      id: '/operator/model-health'
      path: '/operator/model-health'
      fullPath: '/operator/model-health'
      preLoaderRoute: typeof OperatorModelHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$regionId': {
      id: '/r/$regionId'
      path: '/r/$regionId'
      fullPath: '/r/$regionId'
      preLoaderRoute: typeof RRegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/confirm': {
      id: '/subscriptions/confirm'
      path: '/subscriptions/confirm'
      fullPath: '/subscriptions/confirm'
      preLoaderRoute: typeof SubscriptionsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/manage': {
      id: '/subscriptions/manage'
      path: '/subscriptions/manage'
      fullPath: '/subscriptions/manage'
      preLoaderRoute: typeof SubscriptionsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/unsubscribe': {
      id: '/subscriptions/unsubscribe'
      path: '/subscriptions/unsubscribe'
      fullPath: '/subscriptions/unsubscribe'
      preLoaderRoute: typeof SubscriptionsUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$regionId/': {
      id: '/r/$regionId/'
      path: '/'
      fullPath: '/r/$regionId/'
      preLoaderRoute: typeof RRegionIdIndexRouteImport
      parentRoute: typeof RRegionIdRoute
    }
    '/r/$regionId/s/$stationId': {
      id: '/r/$regionId/s/$stationId'
      path: '/s/$stationId'
      fullPath: '/r/$regionId/s/$stationId'
      preLoaderRoute: typeof RRegionIdSStationIdRouteImport
      parentRoute: typeof RRegionIdRoute
    }
    '/r/$regionId/s/$stationId/': {
      id: '/r/$regionId/s/$stationId/'
      path: '/'
      fullPath: '/r/$regionId/s/$stationId/'
      preLoaderRoute: typeof RRegionIdSStationIdIndexRouteImport
      parentRoute: typeof RRegionIdSStationIdRoute
    }
    '/r/$regionId/s/$stationId/forecast': {
      id: '/r/$regionId/s/$stationId/forecast'
      path: '/forecast'
      fullPath: '/r/$regionId/s/$stationId/forecast'
      preLoaderRoute: typeof RRegionIdSStationIdForecastRouteImport
      parentRoute: typeof RRegionIdSStationIdRoute
    }
  }
}

interface RRegionIdSStationIdRouteChildren {
  RRegionIdSStationIdForecastRoute: typeof RRegionIdSStationIdForecastRoute
  RRegionIdSStationIdIndexRoute: typeof RRegionIdSStationIdIndexRoute
}

const RRegionIdSStationIdRouteChildren: RRegionIdSStationIdRouteChildren = {
  RRegionIdSStationIdForecastRoute: RRegionIdSStationIdForecastRoute,
  RRegionIdSStationIdIndexRoute: RRegionIdSStationIdIndexRoute,
}

const RRegionIdSStationIdRouteWithChildren =
  RRegionIdSStationIdRoute._addFileChildren(RRegionIdSStationIdRouteChildren)

interface RRegionIdRouteChildren {
  RRegionIdIndexRoute: typeof RRegionIdIndexRoute
  RRegionIdSStationIdRoute: typeof RRegionIdSStationIdRouteWithChildren
}

const RRegionIdRouteChildren: RRegionIdRouteChildren = {
  RRegionIdIndexRoute: RRegionIdIndexRoute,
  RRegionIdSStationIdRoute: RRegionIdSStationIdRouteWithChildren,
}

const RRegionIdRouteWithChildren = RRegionIdRoute._addFileChildren(
  RRegionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubscribeRoute: SubscribeRoute,
  OperatorModelHealthRoute: OperatorModelHealthRoute,
  RRegionIdRoute: RRegionIdRouteWithChildren,
  SubscriptionsConfirmRoute: SubscriptionsConfirmRoute,
  SubscriptionsManageRoute: SubscriptionsManageRoute,
  SubscriptionsUnsubscribeRoute: SubscriptionsUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
