/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RRegionIdRouteImport } from './routes/r.$regionId'
import { Route as RRegionIdIndexRouteImport } from './routes/r.$regionId.index'
import { Route as RRegionIdSStationIdRouteImport } from './routes/r.$regionId.s.$stationId'
import { Route as RRegionIdSStationIdIndexRouteImport } from './routes/r.$regionId.s.$stationId.index'
import { Route as RRegionIdSStationIdForecastRouteImport } from './routes/r.$regionId.s.$stationId.forecast'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRegionIdRoute = RRegionIdRouteImport.update({
  id: '/r/$regionId',
  path: '/r/$regionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RRegionIdIndexRoute = RRegionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RRegionIdRoute,
} as any)
const RRegionIdSStationIdRoute = RRegionIdSStationIdRouteImport.update({
  id: '/s/$stationId',
  path: '/s/$stationId',
  getParentRoute: () => RRegionIdRoute,
} as any)
const RRegionIdSStationIdIndexRoute =
  RRegionIdSStationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RRegionIdSStationIdRoute,
  } as any)
const RRegionIdSStationIdForecastRoute =
  RRegionIdSStationIdForecastRouteImport.update({
    id: '/forecast',
    path: '/forecast',
    getParentRoute: () => RRegionIdSStationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$regionId': typeof RRegionIdRouteWithChildren
  '/r/$regionId/': typeof RRegionIdIndexRoute
  '/r/$regionId/s/$stationId': typeof RRegionIdSStationIdRouteWithChildren
  '/r/$regionId/s/$stationId/forecast': typeof RRegionIdSStationIdForecastRoute
  '/r/$regionId/s/$stationId/': typeof RRegionIdSStationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$regionId': typeof RRegionIdIndexRoute
  '/r/$regionId/s/$stationId/forecast': typeof RRegionIdSStationIdForecastRoute
  '/r/$regionId/s/$stationId': typeof RRegionIdSStationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r/$regionId': typeof RRegionIdRouteWithChildren
  '/r/$regionId/': typeof RRegionIdIndexRoute
  '/r/$regionId/s/$stationId': typeof RRegionIdSStationIdRouteWithChildren
  '/r/$regionId/s/$stationId/forecast': typeof RRegionIdSStationIdForecastRoute
  '/r/$regionId/s/$stationId/': typeof RRegionIdSStationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/r/$regionId'
    | '/r/$regionId/'
    | '/r/$regionId/s/$stationId'
    | '/r/$regionId/s/$stationId/forecast'
    | '/r/$regionId/s/$stationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/r/$regionId'
    | '/r/$regionId/s/$stationId/forecast'
    | '/r/$regionId/s/$stationId'
  id:
    | '__root__'
    | '/'
    | '/r/$regionId'
    | '/r/$regionId/'
    | '/r/$regionId/s/$stationId'
    | '/r/$regionId/s/$stationId/forecast'
    | '/r/$regionId/s/$stationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RRegionIdRoute: typeof RRegionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$regionId': {
      id: '/r/$regionId'
      path: '/r/$regionId'
      fullPath: '/r/$regionId'
      preLoaderRoute: typeof RRegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$regionId/': {
      id: '/r/$regionId/'
      path: '/'
      fullPath: '/r/$regionId/'
      preLoaderRoute: typeof RRegionIdIndexRouteImport
      parentRoute: typeof RRegionIdRoute
    }
    '/r/$regionId/s/$stationId': {
      id: '/r/$regionId/s/$stationId'
      path: '/s/$stationId'
      fullPath: '/r/$regionId/s/$stationId'
      preLoaderRoute: typeof RRegionIdSStationIdRouteImport
      parentRoute: typeof RRegionIdRoute
    }
    '/r/$regionId/s/$stationId/': {
      id: '/r/$regionId/s/$stationId/'
      path: '/'
      fullPath: '/r/$regionId/s/$stationId/'
      preLoaderRoute: typeof RRegionIdSStationIdIndexRouteImport
      parentRoute: typeof RRegionIdSStationIdRoute
    }
    '/r/$regionId/s/$stationId/forecast': {
      id: '/r/$regionId/s/$stationId/forecast'
      path: '/forecast'
      fullPath: '/r/$regionId/s/$stationId/forecast'
      preLoaderRoute: typeof RRegionIdSStationIdForecastRouteImport
      parentRoute: typeof RRegionIdSStationIdRoute
    }
  }
}

interface RRegionIdSStationIdRouteChildren {
  RRegionIdSStationIdForecastRoute: typeof RRegionIdSStationIdForecastRoute
  RRegionIdSStationIdIndexRoute: typeof RRegionIdSStationIdIndexRoute
}

const RRegionIdSStationIdRouteChildren: RRegionIdSStationIdRouteChildren = {
  RRegionIdSStationIdForecastRoute: RRegionIdSStationIdForecastRoute,
  RRegionIdSStationIdIndexRoute: RRegionIdSStationIdIndexRoute,
}

const RRegionIdSStationIdRouteWithChildren =
  RRegionIdSStationIdRoute._addFileChildren(RRegionIdSStationIdRouteChildren)

interface RRegionIdRouteChildren {
  RRegionIdIndexRoute: typeof RRegionIdIndexRoute
  RRegionIdSStationIdRoute: typeof RRegionIdSStationIdRouteWithChildren
}

const RRegionIdRouteChildren: RRegionIdRouteChildren = {
  RRegionIdIndexRoute: RRegionIdIndexRoute,
  RRegionIdSStationIdRoute: RRegionIdSStationIdRouteWithChildren,
}

const RRegionIdRouteWithChildren = RRegionIdRoute._addFileChildren(
  RRegionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RRegionIdRoute: RRegionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
